// <auto-generated/>
// Generated from definitions.json by Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Enums
{
    public partial class Field
    {
        public static readonly NumberField Number = new NumberField(nameof(Number), 1);
        public static readonly NumberField AssetsAvailable = new NumberField(nameof(AssetsAvailable), 2);
        public static readonly NumberField AssetsMaximum = new NumberField(nameof(AssetsMaximum), 3);
        public static readonly NumberField AssetsTotal = new NumberField(nameof(AssetsTotal), 4);
        public static readonly NumberField LossUnrealized = new NumberField(nameof(LossUnrealized), 5);
        public static readonly NumberField DebtTotal = new NumberField(nameof(DebtTotal), 6);
        public static readonly NumberField DebtMaximum = new NumberField(nameof(DebtMaximum), 7);
        public static readonly NumberField CoverAvailable = new NumberField(nameof(CoverAvailable), 8);
        public static readonly NumberField LoanOriginationFee = new NumberField(nameof(LoanOriginationFee), 9);
        public static readonly NumberField LoanServiceFee = new NumberField(nameof(LoanServiceFee), 10);
        public static readonly NumberField LatePaymentFee = new NumberField(nameof(LatePaymentFee), 11);
        public static readonly NumberField ClosePaymentFee = new NumberField(nameof(ClosePaymentFee), 12);
        public static readonly NumberField PrincipalOutstanding = new NumberField(nameof(PrincipalOutstanding), 13);
        public static readonly NumberField PrincipalRequested = new NumberField(nameof(PrincipalRequested), 14);
        public static readonly NumberField TotalValueOutstanding = new NumberField(nameof(TotalValueOutstanding), 15);
        public static readonly NumberField PeriodicPayment = new NumberField(nameof(PeriodicPayment), 16);
        public static readonly NumberField ManagementFeeOutstanding = new NumberField(nameof(ManagementFeeOutstanding), 17);
    }
}
