// <auto-generated/>
// This file is auto-generated from definitions.json by Tools/GenerateEnums.
// Do not edit manually. Run: dotnet run --project Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Enums
{
    public partial class Field
    {
        public static readonly CurrencyField BaseAsset = new CurrencyField(nameof(BaseAsset), 1);
        public static readonly CurrencyField QuoteAsset = new CurrencyField(nameof(QuoteAsset), 2);
    }
}
