// <auto-generated/>
// Generated from definitions.json by Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Enums
{
    public partial class Field
    {
        public static readonly Hash128Field EmailHash = new Hash128Field(nameof(EmailHash), 1);
    }
}
