// <auto-generated/>
// This file is auto-generated from definitions.json by Tools/GenerateEnums.
// Do not edit manually. Run: dotnet run --project Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Enums
{
    public partial class Field
    {
        public static readonly Uint32Field NetworkID = new Uint32Field(nameof(NetworkID), 1);
        public static readonly Uint32Field Flags = new Uint32Field(nameof(Flags), 2);
        public static readonly Uint32Field SourceTag = new Uint32Field(nameof(SourceTag), 3);
        public static readonly Uint32Field Sequence = new Uint32Field(nameof(Sequence), 4);
        public static readonly Uint32Field PreviousTxnLgrSeq = new Uint32Field(nameof(PreviousTxnLgrSeq), 5);
        public static readonly Uint32Field LedgerSequence = new Uint32Field(nameof(LedgerSequence), 6);
        public static readonly Uint32Field CloseTime = new Uint32Field(nameof(CloseTime), 7);
        public static readonly Uint32Field ParentCloseTime = new Uint32Field(nameof(ParentCloseTime), 8);
        public static readonly Uint32Field SigningTime = new Uint32Field(nameof(SigningTime), 9);
        public static readonly Uint32Field Expiration = new Uint32Field(nameof(Expiration), 10);
        public static readonly Uint32Field TransferRate = new Uint32Field(nameof(TransferRate), 11);
        public static readonly Uint32Field WalletSize = new Uint32Field(nameof(WalletSize), 12);
        public static readonly Uint32Field OwnerCount = new Uint32Field(nameof(OwnerCount), 13);
        public static readonly Uint32Field DestinationTag = new Uint32Field(nameof(DestinationTag), 14);
        public static readonly Uint32Field LastUpdateTime = new Uint32Field(nameof(LastUpdateTime), 15);
        public static readonly Uint32Field HighQualityIn = new Uint32Field(nameof(HighQualityIn), 16);
        public static readonly Uint32Field HighQualityOut = new Uint32Field(nameof(HighQualityOut), 17);
        public static readonly Uint32Field LowQualityIn = new Uint32Field(nameof(LowQualityIn), 18);
        public static readonly Uint32Field LowQualityOut = new Uint32Field(nameof(LowQualityOut), 19);
        public static readonly Uint32Field QualityIn = new Uint32Field(nameof(QualityIn), 20);
        public static readonly Uint32Field QualityOut = new Uint32Field(nameof(QualityOut), 21);
        public static readonly Uint32Field StampEscrow = new Uint32Field(nameof(StampEscrow), 22);
        public static readonly Uint32Field BondAmount = new Uint32Field(nameof(BondAmount), 23);
        public static readonly Uint32Field LoadFee = new Uint32Field(nameof(LoadFee), 24);
        public static readonly Uint32Field OfferSequence = new Uint32Field(nameof(OfferSequence), 25);
        public static readonly Uint32Field FirstLedgerSequence = new Uint32Field(nameof(FirstLedgerSequence), 26);
        public static readonly Uint32Field LastLedgerSequence = new Uint32Field(nameof(LastLedgerSequence), 27);
        public static readonly Uint32Field TransactionIndex = new Uint32Field(nameof(TransactionIndex), 28);
        public static readonly Uint32Field OperationLimit = new Uint32Field(nameof(OperationLimit), 29);
        public static readonly Uint32Field ReferenceFeeUnits = new Uint32Field(nameof(ReferenceFeeUnits), 30);
        public static readonly Uint32Field ReserveBase = new Uint32Field(nameof(ReserveBase), 31);
        public static readonly Uint32Field ReserveIncrement = new Uint32Field(nameof(ReserveIncrement), 32);
        public static readonly Uint32Field SetFlag = new Uint32Field(nameof(SetFlag), 33);
        public static readonly Uint32Field ClearFlag = new Uint32Field(nameof(ClearFlag), 34);
        public static readonly Uint32Field SignerQuorum = new Uint32Field(nameof(SignerQuorum), 35);
        public static readonly Uint32Field CancelAfter = new Uint32Field(nameof(CancelAfter), 36);
        public static readonly Uint32Field FinishAfter = new Uint32Field(nameof(FinishAfter), 37);
        public static readonly Uint32Field SignerListID = new Uint32Field(nameof(SignerListID), 38);
        public static readonly Uint32Field SettleDelay = new Uint32Field(nameof(SettleDelay), 39);
        public static readonly Uint32Field TicketCount = new Uint32Field(nameof(TicketCount), 40);
        public static readonly Uint32Field TicketSequence = new Uint32Field(nameof(TicketSequence), 41);
        public static readonly Uint32Field NFTokenTaxon = new Uint32Field(nameof(NFTokenTaxon), 42);
        public static readonly Uint32Field MintedNFTokens = new Uint32Field(nameof(MintedNFTokens), 43);
        public static readonly Uint32Field BurnedNFTokens = new Uint32Field(nameof(BurnedNFTokens), 44);
        public static readonly Uint32Field HookStateCount = new Uint32Field(nameof(HookStateCount), 45);
        public static readonly Uint32Field EmitGeneration = new Uint32Field(nameof(EmitGeneration), 46);
        public static readonly Uint32Field VoteWeight = new Uint32Field(nameof(VoteWeight), 48);
        public static readonly Uint32Field FirstNFTokenSequence = new Uint32Field(nameof(FirstNFTokenSequence), 50);
        public static readonly Uint32Field OracleDocumentID = new Uint32Field(nameof(OracleDocumentID), 51);
        public static readonly Uint32Field PermissionValue = new Uint32Field(nameof(PermissionValue), 52);
        public static readonly Uint32Field MutableFlags = new Uint32Field(nameof(MutableFlags), 53);
        public static readonly Uint32Field StartDate = new Uint32Field(nameof(StartDate), 54);
        public static readonly Uint32Field PaymentInterval = new Uint32Field(nameof(PaymentInterval), 55);
        public static readonly Uint32Field GracePeriod = new Uint32Field(nameof(GracePeriod), 56);
        public static readonly Uint32Field PreviousPaymentDueDate = new Uint32Field(nameof(PreviousPaymentDueDate), 57);
        public static readonly Uint32Field NextPaymentDueDate = new Uint32Field(nameof(NextPaymentDueDate), 58);
        public static readonly Uint32Field PaymentRemaining = new Uint32Field(nameof(PaymentRemaining), 59);
        public static readonly Uint32Field PaymentTotal = new Uint32Field(nameof(PaymentTotal), 60);
        public static readonly Uint32Field LoanSequence = new Uint32Field(nameof(LoanSequence), 61);
        public static readonly Uint32Field CoverRateMinimum = new Uint32Field(nameof(CoverRateMinimum), 62);
        public static readonly Uint32Field CoverRateLiquidation = new Uint32Field(nameof(CoverRateLiquidation), 63);
        public static readonly Uint32Field OverpaymentFee = new Uint32Field(nameof(OverpaymentFee), 64);
        public static readonly Uint32Field InterestRate = new Uint32Field(nameof(InterestRate), 65);
        public static readonly Uint32Field LateInterestRate = new Uint32Field(nameof(LateInterestRate), 66);
        public static readonly Uint32Field CloseInterestRate = new Uint32Field(nameof(CloseInterestRate), 67);
        public static readonly Uint32Field OverpaymentInterestRate = new Uint32Field(nameof(OverpaymentInterestRate), 68);
    }
}
