// <auto-generated/>
// Generated from definitions.json by Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Enums
{
    public partial class Field
    {
        public static readonly BlobField PublicKey = new BlobField(nameof(PublicKey), 1);
        public static readonly BlobField MessageKey = new BlobField(nameof(MessageKey), 2);
        public static readonly BlobField SigningPubKey = new BlobField(nameof(SigningPubKey), 3);
        public static readonly BlobField TxnSignature = new BlobField(nameof(TxnSignature), 4, isSigningField: false);
        public static readonly BlobField URI = new BlobField(nameof(URI), 5);
        public static readonly BlobField Signature = new BlobField(nameof(Signature), 6, isSigningField: false);
        public static readonly BlobField Domain = new BlobField(nameof(Domain), 7);
        public static readonly BlobField FundCode = new BlobField(nameof(FundCode), 8);
        public static readonly BlobField RemoveCode = new BlobField(nameof(RemoveCode), 9);
        public static readonly BlobField ExpireCode = new BlobField(nameof(ExpireCode), 10);
        public static readonly BlobField CreateCode = new BlobField(nameof(CreateCode), 11);
        public static readonly BlobField MemoType = new BlobField(nameof(MemoType), 12);
        public static readonly BlobField MemoData = new BlobField(nameof(MemoData), 13);
        public static readonly BlobField MemoFormat = new BlobField(nameof(MemoFormat), 14);
        public static readonly BlobField Fulfillment = new BlobField(nameof(Fulfillment), 16);
        public static readonly BlobField Condition = new BlobField(nameof(Condition), 17);
        public static readonly BlobField MasterSignature = new BlobField(nameof(MasterSignature), 18, isSigningField: false);
        public static readonly BlobField UNLModifyValidator = new BlobField(nameof(UNLModifyValidator), 19);
        public static readonly BlobField ValidatorToDisable = new BlobField(nameof(ValidatorToDisable), 20);
        public static readonly BlobField ValidatorToReEnable = new BlobField(nameof(ValidatorToReEnable), 21);
        public static readonly BlobField HookStateData = new BlobField(nameof(HookStateData), 22);
        public static readonly BlobField HookReturnString = new BlobField(nameof(HookReturnString), 23);
        public static readonly BlobField HookParameterName = new BlobField(nameof(HookParameterName), 24);
        public static readonly BlobField HookParameterValue = new BlobField(nameof(HookParameterValue), 25);
        public static readonly BlobField DIDDocument = new BlobField(nameof(DIDDocument), 26);
        public static readonly BlobField Data = new BlobField(nameof(Data), 27);
        public static readonly BlobField AssetClass = new BlobField(nameof(AssetClass), 28);
        public static readonly BlobField Provider = new BlobField(nameof(Provider), 29);
        public static readonly BlobField MPTokenMetadata = new BlobField(nameof(MPTokenMetadata), 30);
        public static readonly BlobField CredentialType = new BlobField(nameof(CredentialType), 31);
    }
}
