// <auto-generated/>
// Generated from definitions.json by Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Enums
{
    public partial class Field
    {
        public static readonly CurrencyField BaseAsset = new CurrencyField(nameof(BaseAsset), 1);
        public static readonly CurrencyField QuoteAsset = new CurrencyField(nameof(QuoteAsset), 2);
    }
}
