// <auto-generated/>
// This file is auto-generated from definitions.json by Tools/GenerateEnums.
// Do not edit manually. Run: dotnet run --project Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Enums
{
    public partial class Field
    {
        public static readonly IssueField LockingChainIssue = new IssueField(nameof(LockingChainIssue), 1);
        public static readonly IssueField IssuingChainIssue = new IssueField(nameof(IssuingChainIssue), 2);
        public static readonly IssueField Asset = new IssueField(nameof(Asset), 3);
        public static readonly IssueField Asset2 = new IssueField(nameof(Asset2), 4);
    }
}
