// <auto-generated/>
// This file is auto-generated from definitions.json by Tools/GenerateEnums.
// Do not edit manually. Run: dotnet run --project Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Enums
{
    public partial class Field
    {
        public static readonly Uint8Field CloseResolution = new Uint8Field(nameof(CloseResolution), 1);
        public static readonly Uint8Field Method = new Uint8Field(nameof(Method), 2);
        public static readonly Uint8Field Scale = new Uint8Field(nameof(Scale), 4);
        public static readonly Uint8Field AssetScale = new Uint8Field(nameof(AssetScale), 5);
        public static readonly Uint8Field TickSize = new Uint8Field(nameof(TickSize), 16);
        public static readonly Uint8Field UNLModifyDisabling = new Uint8Field(nameof(UNLModifyDisabling), 17);
        public static readonly Uint8Field HookResult = new Uint8Field(nameof(HookResult), 18);
        public static readonly Uint8Field WasLockingChainSend = new Uint8Field(nameof(WasLockingChainSend), 19);
        public static readonly Uint8Field WithdrawalPolicy = new Uint8Field(nameof(WithdrawalPolicy), 20);
    }
}
