// <auto-generated/>
// Generated from definitions.json by Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Enums
{
    public partial class Field
    {
        public static readonly Hash160Field TakerPaysCurrency = new Hash160Field(nameof(TakerPaysCurrency), 1);
        public static readonly Hash160Field TakerPaysIssuer = new Hash160Field(nameof(TakerPaysIssuer), 2);
        public static readonly Hash160Field TakerGetsCurrency = new Hash160Field(nameof(TakerGetsCurrency), 3);
        public static readonly Hash160Field TakerGetsIssuer = new Hash160Field(nameof(TakerGetsIssuer), 4);
    }
}
