// <auto-generated/>
// This file is auto-generated from definitions.json by Tools/GenerateEnums.
// Do not edit manually. Run: dotnet run --project Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Enums
{
    public partial class Field
    {
        public static readonly Uint64Field IndexNext = new Uint64Field(nameof(IndexNext), 1);
        public static readonly Uint64Field IndexPrevious = new Uint64Field(nameof(IndexPrevious), 2);
        public static readonly Uint64Field BookNode = new Uint64Field(nameof(BookNode), 3);
        public static readonly Uint64Field OwnerNode = new Uint64Field(nameof(OwnerNode), 4);
        public static readonly Uint64Field BaseFee = new Uint64Field(nameof(BaseFee), 5);
        public static readonly Uint64Field ExchangeRate = new Uint64Field(nameof(ExchangeRate), 6);
        public static readonly Uint64Field LowNode = new Uint64Field(nameof(LowNode), 7);
        public static readonly Uint64Field HighNode = new Uint64Field(nameof(HighNode), 8);
        public static readonly Uint64Field DestinationNode = new Uint64Field(nameof(DestinationNode), 9);
        public static readonly Uint64Field Cookie = new Uint64Field(nameof(Cookie), 10);
        public static readonly Uint64Field ServerVersion = new Uint64Field(nameof(ServerVersion), 11);
        public static readonly Uint64Field NFTokenOfferNode = new Uint64Field(nameof(NFTokenOfferNode), 12);
        public static readonly Uint64Field EmitBurden = new Uint64Field(nameof(EmitBurden), 13);
        public static readonly Uint64Field HookOn = new Uint64Field(nameof(HookOn), 16);
        public static readonly Uint64Field HookInstructionCount = new Uint64Field(nameof(HookInstructionCount), 17);
        public static readonly Uint64Field HookReturnCode = new Uint64Field(nameof(HookReturnCode), 18);
        public static readonly Uint64Field ReferenceCount = new Uint64Field(nameof(ReferenceCount), 19);
        public static readonly Uint64Field XChainClaimID = new Uint64Field(nameof(XChainClaimID), 20);
        public static readonly Uint64Field XChainAccountCreateCount = new Uint64Field(nameof(XChainAccountCreateCount), 21);
        public static readonly Uint64Field XChainAccountClaimCount = new Uint64Field(nameof(XChainAccountClaimCount), 22);
        public static readonly Uint64Field AssetPrice = new Uint64Field(nameof(AssetPrice), 23);
        public static readonly Uint64Field MaximumAmount = new Uint64Field(nameof(MaximumAmount), 24);
        public static readonly Uint64Field OutstandingAmount = new Uint64Field(nameof(OutstandingAmount), 25);
        public static readonly Uint64Field MPTAmount = new Uint64Field(nameof(MPTAmount), 26);
        public static readonly Uint64Field IssuerNode = new Uint64Field(nameof(IssuerNode), 27);
        public static readonly Uint64Field SubjectNode = new Uint64Field(nameof(SubjectNode), 28);
        public static readonly Uint64Field LockedAmount = new Uint64Field(nameof(LockedAmount), 29);
        public static readonly Uint64Field VaultNode = new Uint64Field(nameof(VaultNode), 30);
        public static readonly Uint64Field LoanBrokerNode = new Uint64Field(nameof(LoanBrokerNode), 31);
    }
}
