// <auto-generated/>
// This file is auto-generated from definitions.json by Tools/GenerateEnums.
// Do not edit manually. Run: dotnet run --project Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Enums
{
    public partial class Field
    {
        public static readonly Hash192Field MPTokenIssuanceID = new Hash192Field(nameof(MPTokenIssuanceID), 1);
        public static readonly Hash192Field ShareMPTID = new Hash192Field(nameof(ShareMPTID), 2);
    }
}
