// <auto-generated/>
// Generated from definitions.json by Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Enums
{
    public partial class Field
    {
        public static readonly XChainBridgeField XChainBridge = new XChainBridgeField(nameof(XChainBridge), 1);
    }
}
