// <auto-generated/>
// This file is auto-generated from definitions.json by Tools/GenerateEnums.
// Do not edit manually. Run: dotnet run --project Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Enums
{
    public partial class Field
    {
        public static readonly StObjectField TransactionMetaData = new StObjectField(nameof(TransactionMetaData), 2);
        public static readonly StObjectField CreatedNode = new StObjectField(nameof(CreatedNode), 3);
        public static readonly StObjectField DeletedNode = new StObjectField(nameof(DeletedNode), 4);
        public static readonly StObjectField ModifiedNode = new StObjectField(nameof(ModifiedNode), 5);
        public static readonly StObjectField PreviousFields = new StObjectField(nameof(PreviousFields), 6);
        public static readonly StObjectField FinalFields = new StObjectField(nameof(FinalFields), 7);
        public static readonly StObjectField NewFields = new StObjectField(nameof(NewFields), 8);
        public static readonly StObjectField TemplateEntry = new StObjectField(nameof(TemplateEntry), 9);
        public static readonly StObjectField Memo = new StObjectField(nameof(Memo), 10);
        public static readonly StObjectField SignerEntry = new StObjectField(nameof(SignerEntry), 11);
        public static readonly StObjectField NFToken = new StObjectField(nameof(NFToken), 12);
        public static readonly StObjectField EmitDetails = new StObjectField(nameof(EmitDetails), 13);
        public static readonly StObjectField Hook = new StObjectField(nameof(Hook), 14);
        public static readonly StObjectField Permission = new StObjectField(nameof(Permission), 15);
        public static readonly StObjectField Signer = new StObjectField(nameof(Signer), 16);
        public static readonly StObjectField Majority = new StObjectField(nameof(Majority), 18);
        public static readonly StObjectField DisabledValidator = new StObjectField(nameof(DisabledValidator), 19);
        public static readonly StObjectField EmittedTxn = new StObjectField(nameof(EmittedTxn), 20);
        public static readonly StObjectField HookExecution = new StObjectField(nameof(HookExecution), 21);
        public static readonly StObjectField HookDefinition = new StObjectField(nameof(HookDefinition), 22);
        public static readonly StObjectField HookParameter = new StObjectField(nameof(HookParameter), 23);
        public static readonly StObjectField HookGrant = new StObjectField(nameof(HookGrant), 24);
        public static readonly StObjectField VoteEntry = new StObjectField(nameof(VoteEntry), 25);
        public static readonly StObjectField AuctionSlot = new StObjectField(nameof(AuctionSlot), 26);
        public static readonly StObjectField AuthAccount = new StObjectField(nameof(AuthAccount), 27);
        public static readonly StObjectField XChainClaimProofSig = new StObjectField(nameof(XChainClaimProofSig), 28);
        public static readonly StObjectField XChainCreateAccountProofSig = new StObjectField(nameof(XChainCreateAccountProofSig), 29);
        public static readonly StObjectField XChainClaimAttestationCollectionElement = new StObjectField(nameof(XChainClaimAttestationCollectionElement), 30);
        public static readonly StObjectField XChainCreateAccountAttestationCollectionElement = new StObjectField(nameof(XChainCreateAccountAttestationCollectionElement), 31);
        public static readonly StObjectField PriceData = new StObjectField(nameof(PriceData), 32);
        public static readonly StObjectField Credential = new StObjectField(nameof(Credential), 33);
        public static readonly StObjectField RawTransaction = new StObjectField(nameof(RawTransaction), 34);
        public static readonly StObjectField BatchSigner = new StObjectField(nameof(BatchSigner), 35);
        public static readonly StObjectField Book = new StObjectField(nameof(Book), 36);
        public static readonly StObjectField CounterpartySignature = new StObjectField(nameof(CounterpartySignature), 37, isSigningField: false);
    }
}
