// <auto-generated/>
// This file is auto-generated from definitions.json by Tools/GenerateEnums.
// Do not edit manually. Run: dotnet run --project Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Enums
{
    public partial class Field
    {
        public static readonly AccountIdField Account = new AccountIdField(nameof(Account), 1);
        public static readonly AccountIdField Owner = new AccountIdField(nameof(Owner), 2);
        public static readonly AccountIdField Destination = new AccountIdField(nameof(Destination), 3);
        public static readonly AccountIdField Issuer = new AccountIdField(nameof(Issuer), 4);
        public static readonly AccountIdField Authorize = new AccountIdField(nameof(Authorize), 5);
        public static readonly AccountIdField Unauthorize = new AccountIdField(nameof(Unauthorize), 6);
        public static readonly AccountIdField RegularKey = new AccountIdField(nameof(RegularKey), 8);
        public static readonly AccountIdField NFTokenMinter = new AccountIdField(nameof(NFTokenMinter), 9);
        public static readonly AccountIdField EmitCallback = new AccountIdField(nameof(EmitCallback), 10);
        public static readonly AccountIdField Holder = new AccountIdField(nameof(Holder), 11);
        public static readonly AccountIdField Delegate = new AccountIdField(nameof(Delegate), 12);
        public static readonly AccountIdField HookAccount = new AccountIdField(nameof(HookAccount), 16);
        public static readonly AccountIdField OtherChainSource = new AccountIdField(nameof(OtherChainSource), 18);
        public static readonly AccountIdField OtherChainDestination = new AccountIdField(nameof(OtherChainDestination), 19);
        public static readonly AccountIdField AttestationSignerAccount = new AccountIdField(nameof(AttestationSignerAccount), 20);
        public static readonly AccountIdField AttestationRewardAccount = new AccountIdField(nameof(AttestationRewardAccount), 21);
        public static readonly AccountIdField LockingChainDoor = new AccountIdField(nameof(LockingChainDoor), 22);
        public static readonly AccountIdField IssuingChainDoor = new AccountIdField(nameof(IssuingChainDoor), 23);
        public static readonly AccountIdField Subject = new AccountIdField(nameof(Subject), 24);
        public static readonly AccountIdField Borrower = new AccountIdField(nameof(Borrower), 25);
        public static readonly AccountIdField Counterparty = new AccountIdField(nameof(Counterparty), 26);
    }
}
