// <auto-generated/>
// Generated from definitions.json by Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Enums
{
    public partial class Field
    {
        public static readonly Hash256Field LedgerHash = new Hash256Field(nameof(LedgerHash), 1);
        public static readonly Hash256Field ParentHash = new Hash256Field(nameof(ParentHash), 2);
        public static readonly Hash256Field TransactionHash = new Hash256Field(nameof(TransactionHash), 3);
        public static readonly Hash256Field AccountHash = new Hash256Field(nameof(AccountHash), 4);
        public static readonly Hash256Field PreviousTxnID = new Hash256Field(nameof(PreviousTxnID), 5);
        public static readonly Hash256Field LedgerIndex = new Hash256Field(nameof(LedgerIndex), 6);
        public static readonly Hash256Field WalletLocator = new Hash256Field(nameof(WalletLocator), 7);
        public static readonly Hash256Field RootIndex = new Hash256Field(nameof(RootIndex), 8);
        public static readonly Hash256Field AccountTxnID = new Hash256Field(nameof(AccountTxnID), 9);
        public static readonly Hash256Field NFTokenID = new Hash256Field(nameof(NFTokenID), 10);
        public static readonly Hash256Field EmitParentTxnID = new Hash256Field(nameof(EmitParentTxnID), 11);
        public static readonly Hash256Field EmitNonce = new Hash256Field(nameof(EmitNonce), 12);
        public static readonly Hash256Field EmitHookHash = new Hash256Field(nameof(EmitHookHash), 13);
        public static readonly Hash256Field AMMID = new Hash256Field(nameof(AMMID), 14);
        public static readonly Hash256Field BookDirectory = new Hash256Field(nameof(BookDirectory), 16);
        public static readonly Hash256Field InvoiceID = new Hash256Field(nameof(InvoiceID), 17);
        public static readonly Hash256Field Nickname = new Hash256Field(nameof(Nickname), 18);
        public static readonly Hash256Field Amendment = new Hash256Field(nameof(Amendment), 19);
        public static readonly Hash256Field Digest = new Hash256Field(nameof(Digest), 21);
        public static readonly Hash256Field Channel = new Hash256Field(nameof(Channel), 22);
        public static readonly Hash256Field ConsensusHash = new Hash256Field(nameof(ConsensusHash), 23);
        public static readonly Hash256Field CheckID = new Hash256Field(nameof(CheckID), 24);
        public static readonly Hash256Field ValidatedHash = new Hash256Field(nameof(ValidatedHash), 25);
        public static readonly Hash256Field PreviousPageMin = new Hash256Field(nameof(PreviousPageMin), 26);
        public static readonly Hash256Field NextPageMin = new Hash256Field(nameof(NextPageMin), 27);
        public static readonly Hash256Field NFTokenBuyOffer = new Hash256Field(nameof(NFTokenBuyOffer), 28);
        public static readonly Hash256Field NFTokenSellOffer = new Hash256Field(nameof(NFTokenSellOffer), 29);
        public static readonly Hash256Field HookStateKey = new Hash256Field(nameof(HookStateKey), 30);
        public static readonly Hash256Field HookHash = new Hash256Field(nameof(HookHash), 31);
        public static readonly Hash256Field HookNamespace = new Hash256Field(nameof(HookNamespace), 32);
        public static readonly Hash256Field HookSetTxnID = new Hash256Field(nameof(HookSetTxnID), 33);
        public static readonly Hash256Field DomainID = new Hash256Field(nameof(DomainID), 34);
        public static readonly Hash256Field VaultID = new Hash256Field(nameof(VaultID), 35);
        public static readonly Hash256Field ParentBatchID = new Hash256Field(nameof(ParentBatchID), 36);
        public static readonly Hash256Field LoanBrokerID = new Hash256Field(nameof(LoanBrokerID), 37);
        public static readonly Hash256Field LoanID = new Hash256Field(nameof(LoanID), 38);
    }
}
