// <auto-generated/>
// This file is auto-generated from definitions.json by Tools/GenerateEnums.
// Do not edit manually. Run: dotnet run --project Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Enums
{
    public partial class Field
    {
        public static readonly Vector256Field Indexes = new Vector256Field(nameof(Indexes), 1);
        public static readonly Vector256Field Hashes = new Vector256Field(nameof(Hashes), 2);
        public static readonly Vector256Field Amendments = new Vector256Field(nameof(Amendments), 3);
        public static readonly Vector256Field NFTokenOffers = new Vector256Field(nameof(NFTokenOffers), 4);
        public static readonly Vector256Field CredentialIDs = new Vector256Field(nameof(CredentialIDs), 5);
    }
}
