// <auto-generated/>
// This file is auto-generated from definitions.json by Tools/GenerateEnums.
// Do not edit manually. Run: dotnet run --project Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Enums
{
    public partial class Field
    {
        public static readonly Uint16Field SignerWeight = new Uint16Field(nameof(SignerWeight), 3);
        public static readonly Uint16Field TransferFee = new Uint16Field(nameof(TransferFee), 4);
        public static readonly Uint16Field TradingFee = new Uint16Field(nameof(TradingFee), 5);
        public static readonly Uint16Field DiscountedFee = new Uint16Field(nameof(DiscountedFee), 6);
        public static readonly Uint16Field Version = new Uint16Field(nameof(Version), 16);
        public static readonly Uint16Field HookStateChangeCount = new Uint16Field(nameof(HookStateChangeCount), 17);
        public static readonly Uint16Field HookEmitCount = new Uint16Field(nameof(HookEmitCount), 18);
        public static readonly Uint16Field HookExecutionIndex = new Uint16Field(nameof(HookExecutionIndex), 19);
        public static readonly Uint16Field HookApiVersion = new Uint16Field(nameof(HookApiVersion), 20);
        public static readonly Uint16Field LedgerFixType = new Uint16Field(nameof(LedgerFixType), 21);
        public static readonly Uint16Field ManagementFeeRate = new Uint16Field(nameof(ManagementFeeRate), 22);
    }
}
