// <auto-generated/>
// This file is auto-generated from definitions.json by Tools/GenerateEnums.
// Do not edit manually. Run: dotnet run --project Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Enums
{
    public partial class Field
    {
        public static readonly AmountField Amount = new AmountField(nameof(Amount), 1);
        public static readonly AmountField Balance = new AmountField(nameof(Balance), 2);
        public static readonly AmountField LimitAmount = new AmountField(nameof(LimitAmount), 3);
        public static readonly AmountField TakerPays = new AmountField(nameof(TakerPays), 4);
        public static readonly AmountField TakerGets = new AmountField(nameof(TakerGets), 5);
        public static readonly AmountField LowLimit = new AmountField(nameof(LowLimit), 6);
        public static readonly AmountField HighLimit = new AmountField(nameof(HighLimit), 7);
        public static readonly AmountField Fee = new AmountField(nameof(Fee), 8);
        public static readonly AmountField SendMax = new AmountField(nameof(SendMax), 9);
        public static readonly AmountField DeliverMin = new AmountField(nameof(DeliverMin), 10);
        public static readonly AmountField Amount2 = new AmountField(nameof(Amount2), 11);
        public static readonly AmountField BidMin = new AmountField(nameof(BidMin), 12);
        public static readonly AmountField BidMax = new AmountField(nameof(BidMax), 13);
        public static readonly AmountField MinimumOffer = new AmountField(nameof(MinimumOffer), 16);
        public static readonly AmountField RippleEscrow = new AmountField(nameof(RippleEscrow), 17);
        public static readonly AmountField DeliveredAmount = new AmountField(nameof(DeliveredAmount), 18);
        public static readonly AmountField NFTokenBrokerFee = new AmountField(nameof(NFTokenBrokerFee), 19);
        public static readonly AmountField BaseFeeDrops = new AmountField(nameof(BaseFeeDrops), 22);
        public static readonly AmountField ReserveBaseDrops = new AmountField(nameof(ReserveBaseDrops), 23);
        public static readonly AmountField ReserveIncrementDrops = new AmountField(nameof(ReserveIncrementDrops), 24);
        public static readonly AmountField LPTokenOut = new AmountField(nameof(LPTokenOut), 25);
        public static readonly AmountField LPTokenIn = new AmountField(nameof(LPTokenIn), 26);
        public static readonly AmountField EPrice = new AmountField(nameof(EPrice), 27);
        public static readonly AmountField Price = new AmountField(nameof(Price), 28);
        public static readonly AmountField SignatureReward = new AmountField(nameof(SignatureReward), 29);
        public static readonly AmountField MinAccountCreateAmount = new AmountField(nameof(MinAccountCreateAmount), 30);
        public static readonly AmountField LPTokenBalance = new AmountField(nameof(LPTokenBalance), 31);
    }
}
