// <auto-generated/>
// Generated from definitions.json by Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Enums
{
    public partial class Field
    {
        public static readonly StArrayField Signers = new StArrayField(nameof(Signers), 3, isSigningField: false);
        public static readonly StArrayField SignerEntries = new StArrayField(nameof(SignerEntries), 4);
        public static readonly StArrayField Template = new StArrayField(nameof(Template), 5);
        public static readonly StArrayField Necessary = new StArrayField(nameof(Necessary), 6);
        public static readonly StArrayField Sufficient = new StArrayField(nameof(Sufficient), 7);
        public static readonly StArrayField AffectedNodes = new StArrayField(nameof(AffectedNodes), 8);
        public static readonly StArrayField Memos = new StArrayField(nameof(Memos), 9);
        public static readonly StArrayField NFTokens = new StArrayField(nameof(NFTokens), 10);
        public static readonly StArrayField Hooks = new StArrayField(nameof(Hooks), 11);
        public static readonly StArrayField VoteSlots = new StArrayField(nameof(VoteSlots), 12);
        public static readonly StArrayField AdditionalBooks = new StArrayField(nameof(AdditionalBooks), 13);
        public static readonly StArrayField Majorities = new StArrayField(nameof(Majorities), 16);
        public static readonly StArrayField DisabledValidators = new StArrayField(nameof(DisabledValidators), 17);
        public static readonly StArrayField HookExecutions = new StArrayField(nameof(HookExecutions), 18);
        public static readonly StArrayField HookParameters = new StArrayField(nameof(HookParameters), 19);
        public static readonly StArrayField HookGrants = new StArrayField(nameof(HookGrants), 20);
        public static readonly StArrayField XChainClaimAttestations = new StArrayField(nameof(XChainClaimAttestations), 21);
        public static readonly StArrayField XChainCreateAccountAttestations = new StArrayField(nameof(XChainCreateAccountAttestations), 22);
        public static readonly StArrayField PriceDataSeries = new StArrayField(nameof(PriceDataSeries), 24);
        public static readonly StArrayField AuthAccounts = new StArrayField(nameof(AuthAccounts), 25);
        public static readonly StArrayField AuthorizeCredentials = new StArrayField(nameof(AuthorizeCredentials), 26);
        public static readonly StArrayField UnauthorizeCredentials = new StArrayField(nameof(UnauthorizeCredentials), 27);
        public static readonly StArrayField AcceptedCredentials = new StArrayField(nameof(AcceptedCredentials), 28);
        public static readonly StArrayField Permissions = new StArrayField(nameof(Permissions), 29);
        public static readonly StArrayField RawTransactions = new StArrayField(nameof(RawTransactions), 30);
        public static readonly StArrayField BatchSigners = new StArrayField(nameof(BatchSigners), 31, isSigningField: false);
    }
}
