// <auto-generated/>
// Generated from definitions.json by Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Enums
{
    public partial class LedgerEntryType
    {
        public static readonly LedgerEntryType Invalid = Add(nameof(Invalid), -1);
        public static readonly LedgerEntryType NFTokenOffer = Add(nameof(NFTokenOffer), 55);
        public static readonly LedgerEntryType Check = Add(nameof(Check), 67);
        public static readonly LedgerEntryType DID = Add(nameof(DID), 73);
        public static readonly LedgerEntryType NegativeUNL = Add(nameof(NegativeUNL), 78);
        public static readonly LedgerEntryType NFTokenPage = Add(nameof(NFTokenPage), 80);
        public static readonly LedgerEntryType SignerList = Add(nameof(SignerList), 83);
        public static readonly LedgerEntryType Ticket = Add(nameof(Ticket), 84);
        public static readonly LedgerEntryType AccountRoot = Add(nameof(AccountRoot), 97);
        public static readonly LedgerEntryType DirectoryNode = Add(nameof(DirectoryNode), 100);
        public static readonly LedgerEntryType Amendments = Add(nameof(Amendments), 102);
        public static readonly LedgerEntryType LedgerHashes = Add(nameof(LedgerHashes), 104);
        public static readonly LedgerEntryType Bridge = Add(nameof(Bridge), 105);
        public static readonly LedgerEntryType Offer = Add(nameof(Offer), 111);
        public static readonly LedgerEntryType DepositPreauth = Add(nameof(DepositPreauth), 112);
        public static readonly LedgerEntryType XChainOwnedClaimID = Add(nameof(XChainOwnedClaimID), 113);
        public static readonly LedgerEntryType RippleState = Add(nameof(RippleState), 114);
        public static readonly LedgerEntryType FeeSettings = Add(nameof(FeeSettings), 115);
        public static readonly LedgerEntryType XChainOwnedCreateAccountClaimID = Add(nameof(XChainOwnedCreateAccountClaimID), 116);
        public static readonly LedgerEntryType Escrow = Add(nameof(Escrow), 117);
        public static readonly LedgerEntryType PayChannel = Add(nameof(PayChannel), 120);
        public static readonly LedgerEntryType AMM = Add(nameof(AMM), 121);
        public static readonly LedgerEntryType MPTokenIssuance = Add(nameof(MPTokenIssuance), 126);
        public static readonly LedgerEntryType MPToken = Add(nameof(MPToken), 127);
        public static readonly LedgerEntryType Oracle = Add(nameof(Oracle), 128);
        public static readonly LedgerEntryType Credential = Add(nameof(Credential), 129);
        public static readonly LedgerEntryType PermissionedDomain = Add(nameof(PermissionedDomain), 130);
        public static readonly LedgerEntryType Delegate = Add(nameof(Delegate), 131);
        public static readonly LedgerEntryType Vault = Add(nameof(Vault), 132);
        public static readonly LedgerEntryType LoanBroker = Add(nameof(LoanBroker), 136);
        public static readonly LedgerEntryType Loan = Add(nameof(Loan), 137);
    }
}
