// <auto-generated/>
// This file is auto-generated from definitions.json by Tools/GenerateEnums.
// Do not edit manually. Run: dotnet run --project Tools/GenerateEnums
#pragma warning disable CS1591
namespace Xrpl.BinaryCodec.Types
{
    public partial class TransactionType
    {
        public static readonly TransactionType Invalid = Add(nameof(Invalid), -1);
        public static readonly TransactionType Payment = Add(nameof(Payment), 0);
        public static readonly TransactionType EscrowCreate = Add(nameof(EscrowCreate), 1);
        public static readonly TransactionType EscrowFinish = Add(nameof(EscrowFinish), 2);
        public static readonly TransactionType AccountSet = Add(nameof(AccountSet), 3);
        public static readonly TransactionType EscrowCancel = Add(nameof(EscrowCancel), 4);
        public static readonly TransactionType SetRegularKey = Add(nameof(SetRegularKey), 5);
        public static readonly TransactionType OfferCreate = Add(nameof(OfferCreate), 7);
        public static readonly TransactionType OfferCancel = Add(nameof(OfferCancel), 8);
        public static readonly TransactionType TicketCreate = Add(nameof(TicketCreate), 10);
        public static readonly TransactionType SignerListSet = Add(nameof(SignerListSet), 12);
        public static readonly TransactionType PaymentChannelCreate = Add(nameof(PaymentChannelCreate), 13);
        public static readonly TransactionType PaymentChannelFund = Add(nameof(PaymentChannelFund), 14);
        public static readonly TransactionType PaymentChannelClaim = Add(nameof(PaymentChannelClaim), 15);
        public static readonly TransactionType CheckCreate = Add(nameof(CheckCreate), 16);
        public static readonly TransactionType CheckCash = Add(nameof(CheckCash), 17);
        public static readonly TransactionType CheckCancel = Add(nameof(CheckCancel), 18);
        public static readonly TransactionType DepositPreauth = Add(nameof(DepositPreauth), 19);
        public static readonly TransactionType TrustSet = Add(nameof(TrustSet), 20);
        public static readonly TransactionType AccountDelete = Add(nameof(AccountDelete), 21);
        public static readonly TransactionType NFTokenMint = Add(nameof(NFTokenMint), 25);
        public static readonly TransactionType NFTokenBurn = Add(nameof(NFTokenBurn), 26);
        public static readonly TransactionType NFTokenCreateOffer = Add(nameof(NFTokenCreateOffer), 27);
        public static readonly TransactionType NFTokenCancelOffer = Add(nameof(NFTokenCancelOffer), 28);
        public static readonly TransactionType NFTokenAcceptOffer = Add(nameof(NFTokenAcceptOffer), 29);
        public static readonly TransactionType Clawback = Add(nameof(Clawback), 30);
        public static readonly TransactionType AMMClawback = Add(nameof(AMMClawback), 31);
        public static readonly TransactionType AMMCreate = Add(nameof(AMMCreate), 35);
        public static readonly TransactionType AMMDeposit = Add(nameof(AMMDeposit), 36);
        public static readonly TransactionType AMMWithdraw = Add(nameof(AMMWithdraw), 37);
        public static readonly TransactionType AMMVote = Add(nameof(AMMVote), 38);
        public static readonly TransactionType AMMBid = Add(nameof(AMMBid), 39);
        public static readonly TransactionType AMMDelete = Add(nameof(AMMDelete), 40);
        public static readonly TransactionType XChainCreateClaimID = Add(nameof(XChainCreateClaimID), 41);
        public static readonly TransactionType XChainCommit = Add(nameof(XChainCommit), 42);
        public static readonly TransactionType XChainClaim = Add(nameof(XChainClaim), 43);
        public static readonly TransactionType XChainAccountCreateCommit = Add(nameof(XChainAccountCreateCommit), 44);
        public static readonly TransactionType XChainAddClaimAttestation = Add(nameof(XChainAddClaimAttestation), 45);
        public static readonly TransactionType XChainAddAccountCreateAttestation = Add(nameof(XChainAddAccountCreateAttestation), 46);
        public static readonly TransactionType XChainModifyBridge = Add(nameof(XChainModifyBridge), 47);
        public static readonly TransactionType XChainCreateBridge = Add(nameof(XChainCreateBridge), 48);
        public static readonly TransactionType DIDSet = Add(nameof(DIDSet), 49);
        public static readonly TransactionType DIDDelete = Add(nameof(DIDDelete), 50);
        public static readonly TransactionType OracleSet = Add(nameof(OracleSet), 51);
        public static readonly TransactionType OracleDelete = Add(nameof(OracleDelete), 52);
        public static readonly TransactionType LedgerStateFix = Add(nameof(LedgerStateFix), 53);
        public static readonly TransactionType MPTokenIssuanceCreate = Add(nameof(MPTokenIssuanceCreate), 54);
        public static readonly TransactionType MPTokenIssuanceDestroy = Add(nameof(MPTokenIssuanceDestroy), 55);
        public static readonly TransactionType MPTokenIssuanceSet = Add(nameof(MPTokenIssuanceSet), 56);
        public static readonly TransactionType MPTokenAuthorize = Add(nameof(MPTokenAuthorize), 57);
        public static readonly TransactionType CredentialCreate = Add(nameof(CredentialCreate), 58);
        public static readonly TransactionType CredentialAccept = Add(nameof(CredentialAccept), 59);
        public static readonly TransactionType CredentialDelete = Add(nameof(CredentialDelete), 60);
        public static readonly TransactionType NFTokenModify = Add(nameof(NFTokenModify), 61);
        public static readonly TransactionType PermissionedDomainSet = Add(nameof(PermissionedDomainSet), 62);
        public static readonly TransactionType PermissionedDomainDelete = Add(nameof(PermissionedDomainDelete), 63);
        public static readonly TransactionType DelegateSet = Add(nameof(DelegateSet), 64);
        public static readonly TransactionType VaultCreate = Add(nameof(VaultCreate), 65);
        public static readonly TransactionType VaultSet = Add(nameof(VaultSet), 66);
        public static readonly TransactionType VaultDelete = Add(nameof(VaultDelete), 67);
        public static readonly TransactionType VaultDeposit = Add(nameof(VaultDeposit), 68);
        public static readonly TransactionType VaultWithdraw = Add(nameof(VaultWithdraw), 69);
        public static readonly TransactionType VaultClawback = Add(nameof(VaultClawback), 70);
        public static readonly TransactionType Batch = Add(nameof(Batch), 71);
        public static readonly TransactionType LoanBrokerSet = Add(nameof(LoanBrokerSet), 74);
        public static readonly TransactionType LoanBrokerDelete = Add(nameof(LoanBrokerDelete), 75);
        public static readonly TransactionType LoanBrokerCoverDeposit = Add(nameof(LoanBrokerCoverDeposit), 76);
        public static readonly TransactionType LoanBrokerCoverWithdraw = Add(nameof(LoanBrokerCoverWithdraw), 77);
        public static readonly TransactionType LoanBrokerCoverClawback = Add(nameof(LoanBrokerCoverClawback), 78);
        public static readonly TransactionType LoanSet = Add(nameof(LoanSet), 80);
        public static readonly TransactionType LoanDelete = Add(nameof(LoanDelete), 81);
        public static readonly TransactionType LoanManage = Add(nameof(LoanManage), 82);
        public static readonly TransactionType LoanPay = Add(nameof(LoanPay), 84);
        public static readonly TransactionType EnableAmendment = Add(nameof(EnableAmendment), 100);
        public static readonly TransactionType SetFee = Add(nameof(SetFee), 101);
        public static readonly TransactionType UNLModify = Add(nameof(UNLModify), 102);
    }
}
