using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.Json;

namespace GenerateEnums;

/// <summary>
/// Reads definitions.json and generates C# enum source files for:
/// - EngineResult.cs (TRANSACTION_RESULTS)
/// - TransactionType.Generated.cs (TRANSACTION_TYPES)
/// - LedgerEntryType.Generated.cs (LEDGER_ENTRY_TYPES)
///
/// Usage: dotnet run --project Tools/GenerateEnums [path-to-definitions.json]
/// If no path is given, defaults to Base/Xrpl.BinaryCodec/Enums/definitions.json
/// </summary>
internal static class Program
{
    private static void Main(string[] args)
    {
        string repoRoot = FindRepoRoot();
        string definitionsPath = args.Length > 0
            ? args[0]
            : Path.Combine(repoRoot, "Base", "Xrpl.BinaryCodec", "Enums", "definitions.json");

        if (!File.Exists(definitionsPath))
        {
            Console.Error.WriteLine($"ERROR: definitions.json not found at: {definitionsPath}");
            Environment.Exit(1);
        }

        string outputDir = Path.Combine(repoRoot, "Base", "Xrpl.BinaryCodec", "Enums");
        string json = File.ReadAllText(definitionsPath);
        using JsonDocument doc = JsonDocument.Parse(json);
        JsonElement root = doc.RootElement;

        GenerateEngineResult(root.GetProperty("TRANSACTION_RESULTS"), outputDir);
        GenerateTransactionType(root.GetProperty("TRANSACTION_TYPES"), outputDir);
        GenerateLedgerEntryType(root.GetProperty("LEDGER_ENTRY_TYPES"), outputDir);

        Console.WriteLine("Done. Generated files in: " + outputDir);
    }

    private static void GenerateEngineResult(JsonElement results, string outputDir)
    {
        List<(string Name, int Code)> entries = new();
        foreach (JsonProperty prop in results.EnumerateObject())
            entries.Add((prop.Name, prop.Value.GetInt32()));

        entries.Sort((a, b) => a.Code.CompareTo(b.Code));

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated from definitions.json by Tools/GenerateEnums");
        sb.AppendLine("namespace Xrpl.BinaryCodec.Enums");
        sb.AppendLine("{");
        sb.AppendLine("    public partial class EngineResult : SerializedEnumItem<byte>");
        sb.AppendLine("    {");
        sb.AppendLine("        public class EngineResultValues : SerializedEnumeration<EngineResult, byte>{}");
        sb.AppendLine("        public static EngineResultValues Values = new EngineResultValues();");
        sb.AppendLine("        private readonly string _description;");
        sb.AppendLine("        public EngineResult(string name, int ordinal, string description = \"\") : base(name, ordinal)");
        sb.AppendLine("        {");
        sb.AppendLine("            _description = description;");
        sb.AppendLine("        }");
        sb.AppendLine("        private static EngineResult Add(string name, int ordinal, string description = \"\")");
        sb.AppendLine("        {");
        sb.AppendLine("            return Values.AddEnum(new EngineResult(name, ordinal, description));");
        sb.AppendLine("        }");
        sb.AppendLine();

        string? currentPrefix = null;
        foreach ((string name, int code) in entries)
        {
            string prefix = GetPrefix(name);
            if (prefix != currentPrefix)
            {
                if (currentPrefix != null) sb.AppendLine();
                sb.AppendLine($"        // ─── {prefix} ───");
                currentPrefix = prefix;
            }
            sb.AppendLine($"        public static readonly EngineResult {name} = Add(nameof({name}), {code});");
        }

        sb.AppendLine();
        sb.AppendLine("        public bool ShouldClaimFee() => Ordinal >= 0;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        string path = Path.Combine(outputDir, "EngineResult.Generated.cs");
        File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
        Console.WriteLine($"  Written: {path} ({entries.Count} entries)");
    }

    private static void GenerateTransactionType(JsonElement types, string outputDir)
    {
        List<(string Name, int Code)> entries = new();
        foreach (JsonProperty prop in types.EnumerateObject())
            entries.Add((prop.Name, prop.Value.GetInt32()));

        entries.Sort((a, b) => a.Code.CompareTo(b.Code));

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated from definitions.json by Tools/GenerateEnums");
        sb.AppendLine("using Xrpl.BinaryCodec.Enums;");
        sb.AppendLine();
        sb.AppendLine("namespace Xrpl.BinaryCodec.Types");
        sb.AppendLine("{");
        sb.AppendLine("    public partial class TransactionType : SerializedEnumItem<ushort>");
        sb.AppendLine("    {");
        sb.AppendLine("        public class Enumeration : SerializedEnumeration<TransactionType, ushort> { }");
        sb.AppendLine("        public static Enumeration Values = new Enumeration();");
        sb.AppendLine("        private TransactionType(string reference, int ordinal) : base(reference, ordinal) { }");
        sb.AppendLine("        private static TransactionType Add(string name, int ordinal)");
        sb.AppendLine("        {");
        sb.AppendLine("            return Values.AddEnum(new TransactionType(name, ordinal));");
        sb.AppendLine("        }");
        sb.AppendLine();

        foreach ((string name, int code) in entries)
            sb.AppendLine($"        public static readonly TransactionType {name} = Add(nameof({name}), {code});");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        string path = Path.Combine(outputDir, "TransactionType.Generated.cs");
        File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
        Console.WriteLine($"  Written: {path} ({entries.Count} entries)");
    }

    private static void GenerateLedgerEntryType(JsonElement types, string outputDir)
    {
        List<(string Name, int Code)> entries = new();
        foreach (JsonProperty prop in types.EnumerateObject())
            entries.Add((prop.Name, prop.Value.GetInt32()));

        entries.Sort((a, b) => a.Code.CompareTo(b.Code));

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated from definitions.json by Tools/GenerateEnums");
        sb.AppendLine("using System.Text.Json.Nodes;");
        sb.AppendLine();
        sb.AppendLine("namespace Xrpl.BinaryCodec.Enums");
        sb.AppendLine("{");
        sb.AppendLine("    public partial class LedgerEntryType : SerializedEnumItem<ushort>");
        sb.AppendLine("    {");
        sb.AppendLine("        public class Enumeration : SerializedEnumeration<LedgerEntryType, ushort>{}");
        sb.AppendLine("        public static Enumeration Values = new Enumeration();");
        sb.AppendLine("        private LedgerEntryType(string name, int ordinal) : base(name, ordinal){}");
        sb.AppendLine("        private static LedgerEntryType Add(string reference, int ordinal)");
        sb.AppendLine("        {");
        sb.AppendLine("            return Values.AddEnum(new LedgerEntryType(reference, ordinal));");
        sb.AppendLine("        }");
        sb.AppendLine();

        foreach ((string name, int code) in entries)
            sb.AppendLine($"        public static readonly LedgerEntryType {name} = Add(nameof({name}), {code});");

        sb.AppendLine();
        sb.AppendLine("        public static LedgerEntryType FromJson(JsonNode jToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            return Values.FromJson(jToken);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        string path = Path.Combine(outputDir, "LedgerEntryType.Generated.cs");
        File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
        Console.WriteLine($"  Written: {path} ({entries.Count} entries)");
    }

    private static string GetPrefix(string name)
    {
        if (name.StartsWith("tel")) return "tel";
        if (name.StartsWith("tem")) return "tem";
        if (name.StartsWith("tef")) return "tef";
        if (name.StartsWith("ter")) return "ter";
        if (name.StartsWith("tes")) return "tes";
        if (name.StartsWith("tec")) return "tec";
        return "unknown";
    }

    private static string FindRepoRoot()
    {
        string? dir = AppContext.BaseDirectory;
        while (dir != null)
        {
            if (Directory.Exists(Path.Combine(dir, ".git")))
                return dir;
            if (File.Exists(Path.Combine(dir, "Base", "Xrpl.BinaryCodec", "Enums", "definitions.json")))
                return dir;
            dir = Directory.GetParent(dir)?.FullName;
        }

        dir = Directory.GetCurrentDirectory();
        while (dir != null)
        {
            if (Directory.Exists(Path.Combine(dir, ".git")))
                return dir;
            dir = Directory.GetParent(dir)?.FullName;
        }

        return Directory.GetCurrentDirectory();
    }
}
