using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.Json;

namespace GenerateEnums;

/// <summary>
/// Reads definitions.json and generates partial C# enum source files for:
/// - EngineResult.Generated.cs (TRANSACTION_RESULTS)
/// - TransactionType.Generated.cs (TRANSACTION_TYPES)
/// - LedgerEntryType.Generated.cs (LEDGER_ENTRY_TYPES)
///
/// Each generated file contains only the static readonly field declarations.
/// Infrastructure (Values, constructor, Add method) lives in the hand-written partial file.
///
/// Usage: dotnet run --project Tools/GenerateEnums [path-to-definitions.json]
/// If no path is given, defaults to Base/Xrpl.BinaryCodec/Enums/definitions.json
/// </summary>
internal static class Program
{
    private static void Main(string[] args)
    {
        string repoRoot = FindRepoRoot();
        string definitionsPath = args.Length > 0
            ? args[0]
            : Path.Combine(repoRoot, "Base", "Xrpl.BinaryCodec", "Enums", "definitions.json");

        if (!File.Exists(definitionsPath))
        {
            Console.Error.WriteLine($"ERROR: definitions.json not found at: {definitionsPath}");
            Environment.Exit(1);
        }

        string outputDir = Path.Combine(repoRoot, "Base", "Xrpl.BinaryCodec", "Enums");
        string json = File.ReadAllText(definitionsPath);
        using JsonDocument doc = JsonDocument.Parse(json);
        JsonElement root = doc.RootElement;

        GenerateEngineResult(root.GetProperty("TRANSACTION_RESULTS"), outputDir);
        GenerateTransactionType(root.GetProperty("TRANSACTION_TYPES"), outputDir);
        GenerateLedgerEntryType(root.GetProperty("LEDGER_ENTRY_TYPES"), outputDir);

        Console.WriteLine("Done. Generated files in: " + outputDir);
    }

    private static void GenerateEngineResult(JsonElement results, string outputDir)
    {
        List<(string Name, int Code)> entries = new();
        foreach (JsonProperty prop in results.EnumerateObject())
            entries.Add((prop.Name, prop.Value.GetInt32()));

        entries.Sort((a, b) => a.Code.CompareTo(b.Code));

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated from definitions.json by Tools/GenerateEnums");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine("namespace Xrpl.BinaryCodec.Enums");
        sb.AppendLine("{");
        sb.AppendLine("    public partial class EngineResult");
        sb.AppendLine("    {");

        string? currentPrefix = null;
        foreach ((string name, int code) in entries)
        {
            string prefix = GetPrefix(name);
            if (prefix != currentPrefix)
            {
                if (currentPrefix != null) sb.AppendLine();
                sb.AppendLine($"        // ─── {prefix} ───");
                currentPrefix = prefix;
            }
            sb.AppendLine($"        public static readonly EngineResult {name} = Add(nameof({name}), {code});");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        string path = Path.Combine(outputDir, "EngineResult.Generated.cs");
        File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
        Console.WriteLine($"  Written: {path} ({entries.Count} entries)");
    }

    private static void GenerateTransactionType(JsonElement types, string outputDir)
    {
        List<(string Name, int Code)> entries = new();
        foreach (JsonProperty prop in types.EnumerateObject())
            entries.Add((prop.Name, prop.Value.GetInt32()));

        entries.Sort((a, b) => a.Code.CompareTo(b.Code));

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated from definitions.json by Tools/GenerateEnums");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine("namespace Xrpl.BinaryCodec.Types");
        sb.AppendLine("{");
        sb.AppendLine("    public partial class TransactionType");
        sb.AppendLine("    {");

        foreach ((string name, int code) in entries)
            sb.AppendLine($"        public static readonly TransactionType {name} = Add(nameof({name}), {code});");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        string path = Path.Combine(outputDir, "TransactionType.Generated.cs");
        File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
        Console.WriteLine($"  Written: {path} ({entries.Count} entries)");
    }

    private static void GenerateLedgerEntryType(JsonElement types, string outputDir)
    {
        List<(string Name, int Code)> entries = new();
        foreach (JsonProperty prop in types.EnumerateObject())
            entries.Add((prop.Name, prop.Value.GetInt32()));

        entries.Sort((a, b) => a.Code.CompareTo(b.Code));

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated from definitions.json by Tools/GenerateEnums");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine("namespace Xrpl.BinaryCodec.Enums");
        sb.AppendLine("{");
        sb.AppendLine("    public partial class LedgerEntryType");
        sb.AppendLine("    {");

        foreach ((string name, int code) in entries)
            sb.AppendLine($"        public static readonly LedgerEntryType {name} = Add(nameof({name}), {code});");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        string path = Path.Combine(outputDir, "LedgerEntryType.Generated.cs");
        File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
        Console.WriteLine($"  Written: {path} ({entries.Count} entries)");
    }

    private static string GetPrefix(string name)
    {
        if (name.StartsWith("tel")) return "tel";
        if (name.StartsWith("tem")) return "tem";
        if (name.StartsWith("tef")) return "tef";
        if (name.StartsWith("ter")) return "ter";
        if (name.StartsWith("tes")) return "tes";
        if (name.StartsWith("tec")) return "tec";
        return "unknown";
    }

    private static string FindRepoRoot()
    {
        string? dir = AppContext.BaseDirectory;
        while (dir != null)
        {
            if (Directory.Exists(Path.Combine(dir, ".git")))
                return dir;
            if (File.Exists(Path.Combine(dir, "Base", "Xrpl.BinaryCodec", "Enums", "definitions.json")))
                return dir;
            dir = Directory.GetParent(dir)?.FullName;
        }

        dir = Directory.GetCurrentDirectory();
        while (dir != null)
        {
            if (Directory.Exists(Path.Combine(dir, ".git")))
                return dir;
            dir = Directory.GetParent(dir)?.FullName;
        }

        return Directory.GetCurrentDirectory();
    }
}
