name: NuGet Release

on:
  push:
    branches: [ release ]

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal --settings test.runsettings --filter "TestU"

    - name: Pack all projects
      run: |
        dotnet pack Xrpl/Xrpl.csproj -c Release --no-build
        dotnet pack Base/Xrpl.AddressCodec/Xrpl.AddressCodec.csproj -c Release --no-build
        dotnet pack Base/Xrpl.BinaryCodec/Xrpl.BinaryCodec.csproj -c Release --no-build
        dotnet pack Base/Xrpl.Keypairs/Xrpl.Keypairs.csproj -c Release --no-build
        dotnet pack Xrpl.X402/Xrpl.X402.csproj -c Release --no-build
        dotnet pack Xrpl.X402.AspNetCore/Xrpl.X402.AspNetCore.csproj -c Release --no-build

    - name: Push to GitHub Packages
      run: dotnet nuget push "**/*.nupkg" --skip-duplicate --source https://nuget.pkg.github.com/StaticBit-io/index.json -k ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to NuGet.org
      run: dotnet nuget push "**/*.nupkg" --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
